name: video-export

services:
  # redis:
  #   container_name: redis
  #   image: 'redis:alpine'
  #   ports:
  #     - '6379:6379'
  server:
    container_name: video-export-server
    image: video-export-server
    build: .
    ports:
      - '3001:3001'
    env_file:
      - .env.production
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: package.json
