services:
  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '6379:6379'
  server:
    build: .
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: package.json
