services:
  server:
    build: .
    ports:
      - '3001:3001'
    environment:
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - EXPORT_DIR=/static
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: package.json
