import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Background } from '@/components/background'
import { Nav } from '@/components/nav'
import { ThemeProvider } from '@/components/theme-provider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex grow flex-col-reverse lg:flex-col">
            <Nav />
            {children}
          </div>
          <Background />
        </ThemeProvider>
      </body>
    </html>
  )
}
